### ISSUE TITLE
引入 ElementPlusResolver后，chrome无法打断点，必须格式化后才能打断点

### ISSUE THREAD

**Issue by Harbour8643** [antfu/unplugin-vue-components#414] opened 2022-06-07 03:46 UTC
![image](https://user-images.githubusercontent.com/16264878/172292490-9291f0de-064e-49df-8295-7d0cf9bdcdf1.png)
![image](https://user-images.githubusercontent.com/16264878/172291455-acbddf74-fdb3-4be9-b465-c9f1f076db33.png)
![image](https://user-images.githubusercontent.com/16264878/172291557-4950121e-ef98-4426-881f-960ac38a8799.png)

**Comment by oui-a11y** [comment] 2022-08-09 06:08
<img width="800" alt="image" src="https://user-images.githubusercontent.com/23490547/183576610-e7d4dc9a-b4b6-47ae-8467-2475a9bc3ac9.png">
通过测试，确实是因为unplugin-vue-components/vite产生此问题，无法使用debugger

**Comment by zhoulangchua** [comment] 2022-09-02 10:04
没有人解决这个bug吗?

**Comment by sxzz** [comment] 2022-09-06 08:37
Duplicate of #219

**Closed by sxzz** 2022-09-06 08:37 UTC
