### ISSUE TITLE
not work in rollup api mode

### ISSUE THREAD

**Issue by cczw2010** [antfu/unplugin-vue-components#459] opened 2022-07-12 08:34 UTC
the same simple options  . work well in rollup runtime, but not auto import in rollup api mode.   
v0.21.1

**Comment by sxzz** [comment] 2022-08-09 06:25
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by sxzz** 2022-08-09 06:25 UTC
