### ISSUE TITLE
tsx组件中丢失sourcemap

### ISSUE THREAD

**Issue by Weilence** [antfu/unplugin-vue-components#395] opened 2022-05-21 08:29 UTC
当使用vite时，在chrome或edge中sourcemap会丢失，无法添加断点
```js
Components({
  dts: true,
}),
```
![image](https://user-images.githubusercontent.com/11787429/169643116-0c894d85-d923-4074-bb10-4d1a369bcc72.png)
但添加了include属性后正常
```js
Components({
  dts: true,
  include: [/\.vue$/],
}),
```
![image](https://user-images.githubusercontent.com/11787429/169643152-16ea13d9-7c6d-43a5-a2ee-778f4c9f1c67.png)

**Comment by sxzz** [comment] 2022-09-06 08:51
Duplicate of https://github.com/antfu/unplugin-vue-components/issues/219

**Closed by sxzz** 2022-09-06 08:51 UTC
