### ISSUE TITLE
module '~page' is not found when i run build script

### ISSUE THREAD

**Issue by kaiser-9527** [antfu/unplugin-vue-components#274] opened 2022-01-06 16:54 UTC
It works on development mode. But when i run build script, got this:

```
error TS2307: Cannot find module '~pages' or its corresponding type declarations.

2 import routes from '~pages'
      
```
and, in vscode, has the same hint

**Comment by sxzz** [comment] 2022-09-06 09:06
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2022-09-06 09:06 UTC
