### ISSUE TITLE
how to solve “(!) `this` has been rewritten to `undefined”  in rollup

### ISSUE THREAD

**Issue by qiuzongyuan** [antfu/unplugin-vue-components#225] opened 2021-12-01 03:43 UTC
![image](https://user-images.githubusercontent.com/53800127/144167754-3ccca8ea-03d8-409f-835d-4aded837d717.png)
![image](https://user-images.githubusercontent.com/53800127/144167820-62e3f44b-beec-4157-965e-26875ea9db62.png)
![image](https://user-images.githubusercontent.com/53800127/144167845-97bb921c-347e-4800-a7f8-39e34df69c42.png)
```
rollup: 2.60.1
ant-design-vue: 3.0.0-alpha.13
unplugin-vue-components: 0.17.2
rollup-plugin-typescript2: 0.31.1
@vue/compiler-sfc: 3.2.22
rollup-plugin-vue: 6.0.0
```

**Comment by antfu** [comment] 2021-12-01 06:00
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-12-01 06:00 UTC
