### ISSUE TITLE
cannot find name

### ISSUE THREAD

**Issue by whace** [antfu/unplugin-vue-components#222] opened 2021-11-29 14:39 UTC
when i use jsx.  cannot find name 'ElButton'.

**Comment by antfu** [comment] 2021-11-29 16:10
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-29 16:10 UTC

**Comment by whace** [comment] 2021-11-30 01:24
![1](https://user-images.githubusercontent.com/20571798/143968409-386e8c40-5233-4bcc-8d8a-c897eaa84314.png)
components.d.ts has generated, and components.d.ts has add to my tsconfig.json under includes.

**Comment by whace** [comment] 2021-11-30 01:48
#221
