### ISSUE TITLE
Invoking Loading with a service in element-plus has some problems

### ISSUE THREAD

**Issue by lyh19980329** [antfu/unplugin-vue-components#218] opened 2021-11-17 06:55 UTC
In my project,I use axios and element-plus.

such as in axios file
`import { ElLoading } from 'element-plus'`
`import type { ILoadingInstance } from 'element-plus'`
`let loading`
`axios.interceptors.request.use(`
`      (config) => {`
`          loading = ElLoading.service({`
`            lock: true,`
`            text: 'Loading',`
`            background: 'rgba(0, 0, 0, 0.7)'`
`          })`
`        return config`
`      },`
`      (err) => {`
`        return err`
`      }`
`    )`

`axios.interceptors.response.use(`
`      (res) => {`
`        loading?.close()`
`        const data = res.data`
`        return data`
`      },`
`      (err) => {`
`        loading?.close()`
`        if (err.response.status === 404) {`
`          console.log('404~')`
`        }`
`        return err`
`      }`
`    )`

when I use El-Loading like this.The plugins cannot auto import his relative style.
i must import it  in base.scss
`@import '~element-plus/theme-chalk/el-loading.css'`

**Comment by qc-z** [comment] 2021-11-22 01:18
see: [vite-plugin-style-import](https://github.com/anncwb/vite-plugin-style-import)

**Comment by antfu** [comment] 2021-11-22 02:23
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-22 02:23 UTC
