### ISSUE TITLE
dirs

### ISSUE THREAD

**Issue by RonLeeLi** [antfu/unplugin-vue-components#266] opened 2021-12-25 07:33 UTC
"vite-plugin-components": "0.13.2",

  viteComponents({
    dirs: ['src/components', 'src/pages/**/components'],
    customComponentResolvers: [VantResolver()],
  }),

in 'src/components' ,  use parent directory as name for index components

but

use link 'src/pages/**/components'   can‘t  use parent directory as name for index components. 
[Vue warn]: Failed to resolve component

**Comment by sxzz** [comment] 2022-09-06 09:10
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2022-09-06 09:10 UTC
Labels: needs reproduction
