### ISSUE TITLE
使用pnpm安装依赖的项目报错

### ISSUE THREAD

**Issue by coolphk** [antfu/unplugin-vue-components#306] opened 2022-02-11 02:59 UTC
使用pnpm安装依赖的项目运行时报错
Error: Missing "./es" export in "vant" package
    at bail (D:\workspace\webstorm\vue3\regulatory-platform-mobile\node_modules\.pnpm\registry.npmmirror.com+vite@2.6.14_less@4.1.2\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:2
9712:8)

**Comment by LuoRiWuSheng** [comment] 2023-01-27 06:18
目前没遇到过， 清空 node_modules 和lock文件重新试试呢

**Comment by LuoRiWuSheng** [comment] 2023-01-27 06:18
> 目前没遇到过， 清空 node_modules 和lock文件重新试试呢

**Comment by sxzz** [comment] 2023-02-03 06:20
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2023-02-03 06:20 UTC
